# Generated by Django 4.1 on 2022-09-07 14:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_minio"),
    ]

    operations = [
        migrations.AddField(
            model_name="minio",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="minio",
            name="etag",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
