# Generated by Django 4.1 on 2022-09-07 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_minio_created_alter_minio_etag"),
    ]

    operations = [
        migrations.RenameField(
            model_name="minio",
            old_name="etag",
            new_name="filename",
        ),
    ]
